// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwAHQExgrQWCV5JufQJVxoA5raRoxYMA',
    appId: '1:502293836437:web:b7eeae02af634ac8ea619c',
    messagingSenderId: '502293836437',
    projectId: 'heartcare-2a73f',
    authDomain: 'heartcare-2a73f.firebaseapp.com',
    storageBucket: 'heartcare-2a73f.appspot.com',
    measurementId: 'G-J6BP6CYMRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhXbX4lfcnY52p3KtC-ISF_k-eE_7dTY',
    appId: '1:502293836437:android:c6315b0850f10a02ea619c',
    messagingSenderId: '502293836437',
    projectId: 'heartcare-2a73f',
    storageBucket: 'heartcare-2a73f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvd0kqCdUKmQRY2LE1-390SJXSazYat8',
    appId: '1:502293836437:ios:8d11dc10297d8aaaea619c',
    messagingSenderId: '502293836437',
    projectId: 'heartcare-2a73f',
    storageBucket: 'heartcare-2a73f.appspot.com',
    iosBundleId: 'com.example.heartcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvvd0kqCdUKmQRY2LE1-390SJXSazYat8',
    appId: '1:502293836437:ios:be0d151387b541c8ea619c',
    messagingSenderId: '502293836437',
    projectId: 'heartcare-2a73f',
    storageBucket: 'heartcare-2a73f.appspot.com',
    iosBundleId: 'com.example.heartcare.RunnerTests',
  );
}
